version: '3.1'
volumes:
  data:
  capnp-secrets:
secrets:
  ocaml-ci-github-key:
    external: true
services:
  ci:
    image: ocaml-ci-service
    command: --github-app-id 39151 --github-private-key-file /run/secrets/ocaml-ci-github-key --github-account-whitelist "talex5,ocaml-ci,ocaml,mirage,avsm,samoht,kit-ty-kate,tarides,aantron" --confirm above-average --confirm-auto-release 120 --capnp-address=tcp:ci.ocamllabs.io:8102
    environment:
      - "CI_PROFILE=production"
    ports:
      - '8102:9000'
    volumes:
      - 'data:/var/lib/ocurrent'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'capnp-secrets:/capnp-secrets'
    secrets:
      - 'ocaml-ci-github-key'
